BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB  BBBBB XXXXXX BBBBBBBB

BBBBB BBBB
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB