XXXXXXXXX XXXXX
BBBB BBBBBB
BBBB BBBB
XXXXX XXXXXXXXXX

XXXXXX
    BB BBBBBBBB
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
        XXXBB BBBBBBBBBBBB XXXXXXXXXXXX XXXXXXXXXXXXXX BBBBBXXXXXX
            BBBBBB
    XXXXX
    BBBBB
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX


    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX

    XXXXXXXBBBBB BBBBB BBBBBBBBXXXXXXXX
XXXXXXX

XXXXXX
    BBBBBBB BBBBBBBBBBBBB

    BBBBB BBBB
    BBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBB

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX

XXXXXXX