BBBB BBBBBB

XXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX
                        XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX X X XXX XXXXXX XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX