BBBB BBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBB BB BBBBBBBBBBBB gettext(u"You're receiving this email because user %(user_display)s has given your email address to register an account on %(site_domain)s.\n\nTo confirm this is correct, go to %(activate_url)s") SSSSSS SSSSSSSSS SSSS SSSSS SSSSSSS SSSS SSSSSSSSSSSSSSSS SSS SSSSS SSSS SSSSS SSSSSSS SS SSSSSSSS SS SSSSSSS SS SSSSSSSSSSSSSSSS

SS SSSSSSS SSSS SS SSSSSSSS SS SS SSSSSSSSSSSSSSSSBBBBBBBBBBBBBBBBBBBBB BBBBBBB